### ISSUE TITLE
Could we please have a transformation from unix time to a human readable format?

### ISSUE THREAD

**Issue by HolgerAusB** [hdtodd/rtl_watch#8]
High,

rtl_watch is a nice tool, Thank you.

I am using rtl_433 with option `-Mtime:unix:utc`

When starting rtl_watch, it is showing an iso date-time as long as no data is received from mqtt and is changing the format to unix epoch after the first event is read.

![grafik](https://github.com/user-attachments/assets/2db6a8b8-2098-47e2-922a-539bf23515ef)

So I think, rtl_watch is just taking the value from 'time' key and puts it to the display output.

So could we please have a conversion to ISO-formatted date? Maybe as an option --unixtime --isotime

**Comment by hdtodd** [comment]
I think I understand your request, but let me be sure.

If you've set your rtl_433 service configuration with -M time:unix, so that the JSON time stamp is something like 1723042649, you'd like to have the display show  2024-08-07 14:57:29 .  Is that right?

Seems like I should have had it working that way in the first place, and it appears that it would be an easy fix.  So if I understood correctly, I'll fix it to work that way.

**Comment by HolgerAusB** [comment]
Yes, that's what I meant. Thank you

**Comment by hdtodd** [comment]
Oh, I should have said that I don't think I need a command-line option to do this.

The way I intend to implement it is to simply recognize either iso or unix time (as it does now) but display time only in iso format.  Is there a reason you might want to display unix format some time?  I'd like not to add another option to the command line ... it's already a pretty long list.

**Comment by HolgerAusB** [comment]
not for me. I am fine with iso only

**Comment by hdtodd** [comment]
Thanks.  

And I plan to display local time rather than UTC.  Does that work for you?

**Comment by HolgerAusB** [comment]
very nice, yes

**Comment by hdtodd** [comment]
Fixed, I believe.  Now displays local time for first and last record whether incoming messages are in ISO or Unix:UTC format.  Version 3.0.1 includes this fix.

**Comment by HolgerAusB** [comment]
Thank you. I can't test this before Monday, but I am sure it works.

**Comment by HolgerAusB** [comment]
Hi @hdtodd,

hmm, I had a bit time, to make a short test. The first two tries I got an error after the first rtl event and the table freezes, no more data. After adding `-d` to debug this, no more errors. Removing the `-d` and still no errors. Awkward.

I will continue to monitor this and open a new issue, if I can reproduce the error. Until then, here is my program call and the error message

I am using Python 3.10 for Windows 11

```
X:\xxx\rtl_watch>python D:\GIT\rtl_watch\rtl_watch -H example.com -T rtl/event/Pi1 -t

X:\xxx\rtl_watch\rtl_watch:663: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  mqtt = mqtt_client.Client(mqtt_client.CallbackAPIVersion.VERSION1, client_id, clean_session=False)
Connected to MQTT broker host!
Exception in thread Thread-1 (process_msg):
Traceback (most recent call last):
  File "Z:\Users\zzz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "Z:\Users\zzz\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "X:\xxx\rtl_watch\rtl_watch", line 695, in process_msg
    if "model" not in y:
TypeError: argument of type 'int' is not iterable
```

For the initial issue: I confirm, that I have iso datetime format now. Thank you.
